import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AppStoreProvider } from "@/lib/providers/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AppStoreProvider>
            {children}
            <Toaster theme="dark" richColors duration={3000} />
          </AppStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
